# Generated by Django 4.1.5 on 2023-02-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dessert',
            options={'ordering': ('id',), 'verbose_name': 'Десерт', 'verbose_name_plural': 'Десерты'},
        ),
    ]
