# Generated by Django 4.1.5 on 2023-02-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0002_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientinrecipe',
            options={'verbose_name': 'Ингредиент в рецепте', 'verbose_name_plural': 'Ингредиенты в рецептах'},
        ),
    ]
