# Generated by Django 4.1.5 on 2023-02-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0002_alter_dessert_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dessert',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Десерт', 'verbose_name_plural': 'Десерты'},
        ),
    ]
